---
name: Style Autofix

"on":
  workflow_dispatch:

jobs:
  cookstyle-autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install cookstyle
        run: gem install cookstyle
      - name: Run cookstyle autocorrect
        run: cookstyle -A
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "style: auto-fix cookstyle"
          title: "style: auto-fix cookstyle"
          body: |
            Automated cookstyle auto-corrections.
          branch: "style/cookstyle-autofix"
